name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04-arm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dxvk-arm64ec
          path: dxvk-workdir/dxvk-arm64ec.zip
