name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:sid

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: chmod +x build.sh && ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dxvk-arm64ec
          path: dxvk-workdir/dxvk-arm64ec.zip
