name: Build dxvk-arm64ec WCP

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-26.04-arm

    container:
      image: debian:sid

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: |
          apt update
          apt install sudo -y
          chmod +x build.sh
          ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dxvk-arm64ec
          path: dxvk-workdir/install/dxvk-*.wcp

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: DXVK ARM64EC ${{ env.VERSION }}
          files: dxvk-workdir/install/dxvk-*.wcp
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
